apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  # Añade esto para mejor descubrimiento de servicios
  clusterIP: None # Para usar directamente los endpoints
  # type: ClusterIP # Descomenta si necesitas ClusterIP estándar
