apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  namespace: external-secrets
type: Opaque
stringData:
  token: "hvs.CAESILBYr8l9VfymbFoxGabhBOjAWSKn1X9zzIs2gt2CyFS5GicKImh2cy5rajlNSDI0dE9zaTk1bXdnSTZERTdKMEYucWtLOGQQkAM"