apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Servidor de Let's Encrypt (usar staging para pruebas)
    server: https://acme-v02.api.letsencrypt.org/directory
    #  para notificaciones de expiración
    email: atalmendoza03@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
