apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  DB_HOST: "mysql-service"  # ✅ Correcto: nombre del servicio MySQL
  DB_NAME: "atalesdb"
  PORT: "3000"
  EMAIL_FROM: "atalmendoza03@gmail.com"
  FRONTEND_HOST: "frontend-service"  # Se reemplazará automáticamente
  FRONTEND_PORT: "30080"
  NODE_ENV: "production"
