apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  DB_HOST: "mysql-service"  # Nombre del servicio MySQL
  DB_NAME: "atalesdb"
  PORT: "3000"
  EMAIL_FROM: "atalmendoza03@gmail.com"
