apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
data:
  DB_USER: "amF1bg=="  # juan en base64
  DB_PASSWORD: "MTIzNA=="  # 1234 en base64
  GMAIL_APP_PASSWORD: "YXBpR21haWw="  # apiGmail en base64
  SECRET_KEY: "c2VjcmV0b19zdXBlcl9zZWd1cm8="  # secreto_super_seguro en base64
