apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  labels:
    app: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: luca011/negocio-service-atales:prod-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: negocio-secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
