apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecretstores.external-secrets.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets
          image: ghcr.io/external-secrets/external-secrets:v0.9.11
          args:
            - --metrics-addr=:8080  # Cambiado de --metrics-enabled
            - --enable-cluster-store-reconciler=true  # Cambiado de --cluster-sync-period
            - --loglevel=info  # Opcional: para mejor debugging
          env:
            - name: VAULT_ADDR
              value: "https://api.cloud.hashicorp.com/secrets/2023-11-28"
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          imagePullPolicy: IfNotPresent
