apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  - eso-install.yaml       
  - rbac.yaml             
  - service-account.yaml   
  - vault-auth-secret.yaml
  - clustersecretstore.yaml 
  - backend-external-secret.yaml 

# Agregar ordenamiento para asegurar que el namespace se cree primero
generatorOptions:
  disableNameSuffixHash: true
