apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: luca011/auth-service-atales:dev-v2-20250805032958
          env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"

