apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-vault-store
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: DB_NAME
    - secretKey: GMAIL_USER
      remoteRef:
        key: GMAIL_USER
    - secretKey: GMAIL_APP_PASSWORD
      remoteRef:
        key: GMAIL_APP_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef:
        key: SECRET_KEY
