apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atales-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/LucaCostabile/infrastructura-Atales'
    targetRevision: dev
    path: argo-apps/root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
