apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
spec:
  template:
    spec:
      containers:
        - name: business-service
          image: luca011/negocio-service-atales:dev-v2-20250805154947
          env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"

