apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
data:
  CRYPTO_SECRET: {{ BASE64 }}
  DB_PASSWORD: {{ BASE64 }}
  DB_USER: {{ BASE64 }}
  EXTERNAL_API_KEY: {{ BASE64 }}
  GMAIL_APP_PASSWORD: {{ BASE64 }}
  GMAIL_USER: {{ BASE64 }}
  JWT_SECRET_KEY: {{ BASE64 }}
