apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgAIc3SDiGnNcVtAh233wrv8CPxEzLGZCkJcq1O/2UhMUipfVX6mWorulTjiNd/ddX4ErhBdGnZ57fKZLmE2/r87LehJaZkz+hWroOkwHB//2chJic8rKltBau3wYylYcmkzbDyY3LXA6rEJys9Ki/JDja+Lf4Jc1wnswTFCol4PYMDanQBi0x1mpfDCbGEGfAtJe3Yi9rbbfYDAHRlXpD6tb5XT0l+xRFfo9hBozp7SsuBojLSw8eEd97HnuCxyGonBzApBzLgaX31kt79BrbaLqlvQKEVw7A8wS5s4RvKyDa/LDTA6Tk7RTwj44MrES8KAI5R02exbA/TiAQ3Xl2uPtZe1O5jMSZEDJIQFVSOS+NT6lqguwTYk560KOjEGaa2xQnL+hxMlHxlfFzWPaQ6GgY+bIe+3opW2xY0SreeElwmP9GMLtcGk8CL6yN2pbrS5EcaauSLQMvaXJg2rT8+7/YcTkFtVdAcMQy1FVq6TEKC6Xrz5eRPrXI+PL5tXZ1SnK3IMJ7jfnKcWVNLU8cIgnrOtW94sKPi6f4xDK/QAoPtXYH+nACWH880vG04Qj2xRMpnktzGKUV2TDxGSHBTR4wRajQxnlojy4UONnOuCf/tmMsmTfX8NVV/IJWYBBqYDLaLf3m6bgzy2RMzrtNkf/keHOhQoo4UZwEcT1ownjOdN03wXTDp2rylmvoyWecEPdeNPsjBlMfwY8w9l6GQNK8Ltwg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

