apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgCqavxC8JrSGV9kaKSQ2mmM+IpQ9t8FOg7iRyrJWR9gYGM19AjdQ3bxsnIvHSKWSpTbuxV+qbNctEQbabrzP8w65oQF1ll9Ike/N0dMRT9uSLWJ3vxxWBnnmlea2SVD5Mg2YoIj0DY23svuL431rDrjTSho0DDKCZyigcwt+dkjclvvFJsUY0pPYMmHU2K49c36O9UGB1hv2e8pgUh5WG1yH5F1kvYAtK5D+9snK1rf/Xyb5rEvUEMI8eSXQEzF9b89PseOdK8hkuNHvULIHymJgBmPCLgMpisUMflnzv28fYYW14NaOoeyW7teNryg3eZiV8qCJqCgsmqRuqqaOzDRAy5Hld9bH9Laii0iQyaLcjwZXLZfZ78V0VmmkHVBNbxJo/uI3bcWfd/8P37cfCeR48TNAPadG/2dw+WFvWBS1O8HqJAcyc+dddYAaD6kJ3c8nGTbFOKo9K4giyUa6KEVW2CqST6vygQkVDQhIE7AZHiesn1yqmnFWR8fLQi41/J05C5OH/gZKEJsdWMg814OQWBn/0QBUs3rnULv7HDCBcN2KUhZnB9LQV/W88kkC0db+vveTGImCcYCV81hJjbipDQpxmUg7HLcqcerkSP5uCIovTcCgs1uUBGRVOjilmy0h7rofWHJZWHsOhqHxXQSwB6iFMpq2v8JwC6IAAtqczhbnj6OVOz9n7EGGXtdopKnXtMhfvv9jbgMNRIXTXaVh8EXew==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

