apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgA4GV274VFNE91Z0AJN2+V3yHHyIBX5qKffmyvTS+8mRyN4fh8AD2TBH/WbY5jjLKbVqVvggXWuzYl23orASbQJiKJpKGak6mSaBEswPJqg5Bha568e0OOrHKkwmsukw1CAPIgyCDYl8Rs1Qc3TUXUZbESrWYeVv2aMG8QyOQENDF0O8/zzN652zFg/SrzjsvD2iXn+RUXRrzusxZndw4vip22synl+Sa6JFlpqRGmVD+xgPMctKc2TRIc7WyTqKkweZlDs34dTGmO09YHFWKkwOuVv6uGzShVz5279dOPz9v78nO8uBXi2lB3g2bN0Z6BiMqPzrKvNXydntUsJYFlMlymwqxibo7i/Paa1aDZpcgjOHx7CeNVyEsrugmD9N9CxJktpI1nS37xtjdmDMBrTuO/SPqtphuJ8EjBWfiWcrNaL09wbjdzyFQ92uYlefnnyLdMxbCCTpjYq9CiDAIU6v67KJ0NNXb549obisVFsBKn4YDMJEL9ZkF1PyGn+CLZ3yFvTCnZuPmaLqPOdd7c15zgbrRtvXaop9eVFIzGrh6frni8Ulk2G0Ot603b3Xuv7gifEIJC7HfscriheOc5pEdyCtlGnjH4dQTt+Kd/Q8CTgKGzpvPXoQy0MueQRSW00oVgOHgHV5rIqXJOAA8F50bZPhavtEgJph+4OMAoqYF24mWPEcM+AIaxTiezhU74jsUMC6WDFggt252FXAUD1aME53g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

