apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgA6CID4c0wJ9SDOO9z9wirrZ6bySRndbjsVjjexxBFImhGOGrXWVbr4Dz6kx+21mKDPCJSq9GRiHdiaCt3+AfdmgQW68nsdOQzIhD4eCQRWh34KSrsxEwTPwTIxEGQff55U+RQ2Ncno7w8fzL+7NeZLFC2kpKNdCXgWJwqOTdtIy2Sh5phRtp6RbxlVFa0nrE8os/YTvM5eIUUXaDqr5Xkzr1bCp4C3r28kax4rRZQRiY5MBgDEWLrmLf2YpZRTuiaYRyl1I80xgTx7jEigM+IDKi5wgVCqT6WRSvCpZJ60WpDPGEc0PvVuof/ud0XcqE9j0Bf7CFTypmvYQtmsFi1fr9Y7M62qFVokUet9/f4b3XpMP+ac/6iqHVblAfbGKVYk+zCc/0nMnlZdnr6LI3Qvfn1arQ1OlC2m+sf5H1GMS02b8d3PhrvsPEAARV89kDlJFt41hPZr7rdY90h/L+MAvYxnPcKYeXWw5sUQb9sVjf2OEft27DVwUYCAL7JE9lcYEOQzod2J2qdhzF4eu5gzuqBYJBLLFUnmrg8kM4Ju0ualGjBmvGmdp2J877W1PIHlfbna8SFV31myQraupbU0fTk+44jzpu6l8wnuO3DcbQU9Qrl+yzV14rRH1ebSU2XJq/BPF973BG1TSpk15eGWitsS/Rj9UUCF1dcgUETXBDraqmiaso2LyOYE1IC3O8OixvvHrHci3ufZPjusacy3/D3h+A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

