apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBKW0//bJMkou08uVrhH9Y8jPELqOJsycsD0sHcwi0mfgG2b6gaMmKGyQ+O5UlCAa+YOIo3NKzyTDc5BdzWZBW7jufpgydwJafeDGaCLDpbwSDBteIVR/tFvsQpLIwJxqPGh8WNqrsk5AA3HNYd8owtWZzXbb/yOeSWN/Dv29NJPGHkflItKXWiOEmKtg9gpl/0yI7siJRRu+6dImAK+4FW2OUgxJ7MAtdT2aqE95d6bk5tV3TDspPVAoarleiUA6/N+sO4sPn43rg4iSPI91KABy79u7mfTvFJyTb1NbGa91tMZQ14iBRlN+aDR0uadUIhiRXS7GHHPkcU+clOylmR6SEsM+JXUvZi8Lq05QnbnMV2w+qzRUAFeeXcIB0q0pexUx7oZGU8rPGPlf4D3GIPLMeYdpZF/XwvF771hRQAy4zDuJ7a9ObPE4+AFYwsU9ioUv27nlqH/7PmVyNFKgjIG8FouJam0AaFo7t2TiSLpu15SZ1CsQMTmv5Aw5GH8oDiOKV083TUw+eFMiPPco6NYvAXe4+OZweO5yu796+mXlFiKWZHwmU9dOs791yYbrp/MFAnNYp/SUyoXQwFgFIGvdb4+pRe5huyh6hZQin11yLSwMueRxVRRsTOZLqjBqexczpozQPaYqTj6yATq1zZDAqhCqqR1MBQ+rMIdbSdK5LYwzG+xOwCKMKVviIpWORh/GWZeaUuvaB15RhcnIq54wwInQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

