apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBO2Vs1ee2ukQZvLD78xPaN2+Wv3TNorJ5A1ZXvvKOfaWbc4sR7xGkaNcA+YRuduJVTNdOuNxBAwz26CX2+Ngcl0S5WLwAZc34WS7jYUof6fWZu5+x/uYn7//Ra/pz9yQpWsJNFDEDhus2D9AgM5A/hHAvMOa2pwhZziWORZorQnRarpyR/erd5Nu0+Pjxh0sZa1W4NrTpPu5gZAhxNEViHtrKIBHcu0DJDOezGfMv9IlIdleKFRRlDS2ulKVlo/7WBQxB5i9IYqzJ4SoGwAM1YJMOIe4LsKLwtVNi6ee1ez0kkLFutC9CtfrVaHAH62CcgpJwPBOozolJyec3gyVR5Ie/6yM2gDBq16D7HlGlUitRSIXISNywWDcilrMMTpp16FN/cvmZUGtJSCGW+bmiks+ZDhvKqRN3LdhqrB/c1C7TLWDxfJ6a3i/vEzfLXMKLUBgJL8yGh+IB9AYLmpdBoC1lCnTLHHfMSIRRydTvWIGN8J53qM54nA8uhKDVpJ6Q5XjQCij8NbmH9tXIhrKrWGEgPGNVM7r/oeT7W3BkayhzmcQCyL71q6iu7hNiTzM6Uqfsvn8sx3Tc+dJzaP+OvjtYmlzk2vqZFmZH3Mac+INf+C5YJ+yVW376caIzrCmuxyqEt9GPLKK5OvyLNZA1hmZDxonjn1G7zM7UclH6zDV3CHrlbEa1fAaYpgEif13wlcO8d6LqvoMoSz6h+1sIwN6ByIfEFeXRI2TSw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

