apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-secrets
  namespace: dev
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBz375L6cObj9BnPv9OlfC+qHXQ+PvGgyJ9v3eRREs0uz0EmzMxxaHrN6yhBvINDrGd/NtBjFNguLfLP5qVWnN+1cTB3mcwvyt4je40BVVabg9eq/vg/XTcwdWMQobCJdLwnZmk2cc+IwEEIh/2mZ8SD1GvSbU/lwAeP38Fag2bWVZi8FjSmR51Rf97cg4TKBAm6L3VHuOvzWamutSV/QV82mwS3LMYnbUY1HDY13clmaJVEn90wUEzpZTG1xvQOJiTV7jufhDmpV2t+73ofgmg1wtDgoj1btYMDJ0TGYvY7Y4jeXxCGG4IInbRYQmmtjr9is9WGVOO8a+p6CF3XUX9vDisc0SVHMnEDxHKh//sHsIplvqxqpJwbObZpfuvmzmvI7OibJQaVxJYGSZ9uYB7gjSa1fykhJW0bOOOJ+FqLmSTidpVqJNAzaoDd2rtELQBt9VuYOVaU+HAvk8W4+eZT8hJVXTlEQFlH0NymjAPwk5XsX7Yay8N1NyCuFck5aI4kPFSR+VDjO6i0H3vwNoHwfngj0hUkXycZztIPQo1Is9dZH+Zoqtg/IqARIB/41aUbemXT1PWi7mNj/+q0I9W4xdi8FPsDLU7dEL2hAHmSwjfVqxmXrV7b0yHnrWyTNusREXU0e/vbR2wTuNzQ7fPaQd63u1FPBSBWgwpWkvRiZ4oFYfdcClShjfbvQNgLUCjVrhjmHMdSiLOwaRNP5g3GgeXIw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gateway-secrets
      namespace: dev
    type: Opaque

