apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: negocio-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgBYWXht4GD59hG2YoRIvdKQfudPHbpa9wRFEW7FDrA1LNKwdwWavucIjOiPS7mQoPAYcjY/otxKa7pv9oIm1vr+eco54lRV77yv2Uh0jj8fAyGgzgz9t1fzv+FFW5wssL3ASgO/IfXuxCuWiE3uPr5u9OyRH2rKpYHczxdkKv8n3KjRA7ctQJ5qyOGvpjYos4NoROdF92tebpa8+rDin85DPND3Hz+iI61XtaJuxTbqKI8jzVuBh+D1LBHsL5KaMogugtAEQYbLpUPTzv9s30iWUIqVouoIQhf1N0hVbT6MeWubRbCZuOxhQeIobuZ58LioshGJqYLiFABo33CTf2atbdZd9IrdOTtBWembMp0usQvEMa6A9VSfnkDJZlfPwrmRnZvjUbvIQzDjQ/TdAjq/rrvX7uIH4fSB5YanQw04T5SWJJX1SRaNuQCt0IR/efRQzdGRJOw20FHIPzR3z9lTD9cKUrSQ7mYmIKsGsv1r3Dd0Ucw6ZD54qQXkFIIg9302kLtyqQ3qanI//KQDlM49OPpLL0FXGKcpz89bhlmmrHBqwScnqgWbLsHa6lj97XVLrHd+iUYA8903VhcnI7EIp229wTMOf4dLafA71T13KHGINWMTMf8aE7Pm/A+6s98XSLTquQJYhldBs8QWcOssVOzLpe6FkAeo2favL1IXBEJxODahw1DxgOur3OqEKAY8GGad
    DB_USER: AgBiq58vVPozCWMEfyLKEQN8W6WDKg7QIrSV6aaLjxyTDrJ4QWdxX3CygrvJlTgy+kiRen55kOMzgQT+hfH8T4q5ziNogq2fi9jaEQM2l1XvhDWmA8xIqs6fh93hLdWeSeVwIaimSrV1flzuT9D04ib/Za3bR7Ss6Kc/Kw4ogP0eGgz9sxrAjJX2UF46dNQ0kaPy5j3xI5XR7e5IO8sXMf1pGaidqOdYqysZKdf6ZyGK/Z51NmxMgmBaFF6ujxqdxl/Cm8eQRXlrScThhzGVfWstEKxYxWbdOtb49+njUNz931CVgFFycGDOGTCiyU3rbBdCwK4XlFUnyH7+7rNSTsGmRqvML8EgKn+L2VRHIFJfX4GeVeeOPQ+uw+dI9MrUSXoZfyee+kd3136EI7qvLyZoiakSlFmMCHor9hR5G6V5jwbfi8Plzb4uWEQ6DgTV6XvY3dmeTz4/87sCG32q23WWlWJZwyk5Pg/t/CFa1mBXTDNylP0c5kSZNgNWQh3xuPSp182UFZxK7VSrShyJLl2ZgYt65S6Hl5xzQ5gwMf3PUC+aImtZV1rbHDm0pAbJbDAjAW4Yl1VCiXtC1HyZoswtaxc9WkBD3CkjBdhFIytp/qawwmhF2QH5snv7yZhurt6sdmeFm0s7PqOqsoAvP+mVtAkUgoEef8KPyL5Dyf31ZbM+5zbbOdp1bMw8IeBzzJPIoyWn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: negocio-secrets
      namespace: dev
    type: Opaque

