apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: negocio-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCj0+r77BFApsBi9qybM5uqIANi745WHPYmh0lMRNLYEEcwn9WzGGJRUbNv2DtP5htlCq26xfiHrsgCX5bpRitfzGfgZqOvXaCFb7TiUDWvcn7oS2iCsACwaZLsbWXa6sWBquRinaRXl6/NvtBEbfbBJVEOifSvRMAdTNw4GXPH//2OaRizrynRjQULxE1y6Nl8dEARjIWFkjOzw0ImGP2Y5jOtXdpdXjJbflicqbwo/XjpSzHCwsQTl28PdyR7S+RdIf/2X2ED9J9AfbQLAYJGWY9PY0zThr+gtSfI0ChuioIH709IGYa4aPcxY5bQMP01fGI4tAX72ZmSXxGRW/CBe3nANso6EnZskQBPINX2EL/937qfvAymKCM5f3xD7uL1Ht9OxvzAQIz3FvH5xK6OV+pb2YHopdbvxHaaanMkqlI3H1IVhElM73C4GZyyd8QeC7/ukLkWX3pukMgeJq1ELWNovnFoZRi6/gfAEVMebXZ52cg5nZMvrh6dnet4afaO2e5rsvBjPer98YeUkgZpKRmsl6Dyd5uipVUVvGV1bxDxMWsET72dPjnTHkdbhaTi84XKOs/YYcTyfLGEmK0MO5s22zNC+Uz2jtck+tQKvHne4S6AYNbQ/omHzpTJCLDT7tqKMId03rbk0FoE+oMuB8oPWWN+r8WcDrFdMdj94TuGR41rQiFHxZuKBvzPx3r/230z
    DB_USER: AgCsoBB5jLy4b/ZLGVghZnrl7ccOfwBm2dM9/dc38+ORT6MVNj1qjPvGAsSX2kHipovrtcqkTAIvqmutbtviaUE/Lk0AFxvgFDjbMlzoaM25ka89zg45mnjkKiCN1cUvG/ujgjS01vfmqSciQLkiwgShl+Lp09JTij+moonY2YyByf6IjQUc7UVRQEvSj639qcGQHfYNFoYU9ghM3YgmmWl7+AJ3RmJIKt6zDY7l33KjLWLiIWEpYAVns9Ale56dfQuP6syRVv2Xoz/U+aWNBs2Cjw9gD2zxFs/EE0zQdTeAvijZ1lIeUN6tx8l3IM2rHB75ALX3Pq9ZrKy/b2SbPlQApXcdSx7rlizVnTbp81qrVyL/JoQ8cMXmdRT7Ss7vCX0f2jOjjZ4CNgvwaM2hjdlgdFxr19Rk/cmmfFxpni93skC00XSqVvkP08KPvqzasNcfuGQBXnv1CKXyAmlELgqL/6pY1FrpQgqsaODJ7T9ZPbwF2DwNcSQ98ZX6qBeDaeH/VV41JRGAUHQFY3kSNC5WA9T2maLvpKEX406QVspauYZFjci7uIZZArfZmyOiE4Opfo1v6Xr//M+VDnpx4705Rh4dnQDuuIqpUY1TqMQKWpqUqjbp8rqd/Bzs+JrJrqJySz9ekXlJrhuYVnji6O2bU+8E6G1GaNJ8PpbQ6QOK9RHuwtse/YIyK+jd9ZgxgFGOVjdX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: negocio-secrets
      namespace: dev
    type: Opaque

