apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: negocio-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCYM6gUcapo3bEGi7Ji7VJbhkmZXmqAT3BRl9L6JdngFvBaduOB+1xLXrW/sapVnXQZi+cWawUHOI5k9rJJrbL4nN/20D+FeJlwsFyHZnhhWGBGMkq6Xs4rS05cKQiUNIaxKlknf1JlFrzWxaCirMkCqNd389ccVQeH6eJNb2kPVw3OKbhsYV2vXVo+02R3LtGkTJuIp40MfFyRvgqk3SJj0gZWH6epY95km78eZvESwvsOpWacK2cdXDbCYJmbhC17zV3d+QaEWOqcBjeuIZY4P1nCX0FO2KbeMLBlq+Bcmjt0j8pHOdhKRj/YRYZ4ALerJ98HY+kb/K2lLVFGfPr3U8cJhdhfOOSrTDMEoQVzE8L48CxaFAIGw3xHHmyrv0tEQpQdpfbHv2yUMQE0glaYFjewxdAjUZHuWHEuybqABR55e5rVqusXfSia07fOnLGVz0vGZ1kdgdF+i+/P7TUIc/WlKVqj78SoRlN8cHz80kn/e+1EKh1W3beUCZyfHXZdWG+GOn08e5VcwWegE7gKLDaWTKwkzz3fH5hqPCUoY8HCoOLtoNHPi7zG8pnGIUNTX1Ie7a1oMwoUfKtYu7uxy/w9+YHjjLz9dn/olEwQirpIUB8cmHVUWOh0y0RauUUbBypWVP3R7/5BJZNU6yOpdTGsZTUv1VskdEtGyJSa3XQuDIYP8zBLwOAlvoeyHofuFBsW
    DB_USER: AgAvI7N9krT3OHFyq6yS0mMFjCAkT3rdpC1TxAxJo3x/puhVVT5X3g1r411iW6GVV02u1zF7OevrpxOnldMXmUOHm5tKqaPk9LaA0hdAbqLc2hO6eGoswGcQa2mYblKfyCqXWpPIwFkg5L9RC8kD8ABQpJdAvXRCZ7bl1GrhtIxqA9sbGc0LZteupmlyB4frx7aRnrVDhMcXCUuUWrpFm8Qtv7HbCZTUBMfi2ooY3H0gUuNbEpumvlnjrzNJl65yKXQ52brvI0R1g/dQlmKmMx9z0KfRsWZZdkwaf5HvbohXtMi/hzm8JzFli/C+NawdTTnRLGiA/GBVCwPhxHK+qPMYi/hH0+ZRv7g4M7ZckPOVnHvPRTlMaDlMqDKiGEoYiZI+0Emxq2sRXjItlLH/9swPSjw2TcEJNQnrc1L1HpPG63Nr/Esc/TIKc3Vmym7gWSw9FCaYfBDWCpHkVY0BzIxP9kProGTTLX5RdIaTv5wxq7Q7dmQoMpZBX/RAFr2NRAdx/wNn678THCNqhYKhM3sxAa4sfaD9Hxih9/SOxDajOmKM6E/wDMKrRvjeBFeOzlp0rBV9RM64BZypVOv2m0ma3tDHqf5YHf5ggUjvX0eMf7PyOXW5QpT465lCZdBO/gvdXq2AJpFtPr5I0qmN5nAJGY3aKq27+yuKPPX3+bMm3bxZQe1S6pShvj0ArG+AugS2GknA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: negocio-secrets
      namespace: dev
    type: Opaque

