apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb
  namespace: test
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80        # Puerto externo del LoadBalancer
      targetPort: 3000 # Puerto interno donde corre el api-gateway
  type: LoadBalancer
