apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          # Probes optimizadas
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              httpHeaders:
              - name: User-Agent
                value: kube-probe/liveness
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5        # Aumentado de 1s a 5s
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              httpHeaders:
              - name: User-Agent
                value: kube-probe/readiness
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5        # Aumentado de 1s a 5s
            failureThreshold: 3
            successThreshold: 1
          # Variables de entorno opcionales
          env:
          - name: NODE_ENV
            value: "production"
          - name: AUTH_SERVICE_PORT
            value: "3001"
          - name: BUSINESS_SERVICE_PORT
            value: "3002"
      restartPolicy: Always
