resources:
  - deployment-api-gateway.yaml
  - deployment-auth-service.yaml
  - deployment-business-service.yaml
  - service-api-gateway.yaml
  - service-auth-service.yaml
  - service-business-service.yaml
  - deployment-frontend.yaml
  - deployment-mysql.yaml
  - service-frontend.yaml
  - service-mysql.yaml
  - pvc-mysql.yaml
  - configmap-backend.yaml
  - hpa-backend.yaml
