apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_USER: "amF1bg=="               # juan
  DB_PASSWORD: "MTIzNA=="           # 1234
  GMAIL_APP_PASSWORD: "aHR4aiBya2ZnIHBjeGggdW5hYw=="  # apiGmail
  SECRET_KEY: "c2VjcmV0b19zdXBlcl9zZWd1cm8="  # secreto_super_seguro
