apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: luca011/api-gateway-atales:dev-v2-20250805194601
          env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"

