apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LucaCostabile/infrastructura-Atales
    targetRevision: test
    path: overlays/test/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
