apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atales-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/LucaCostabile/infrastructura-Atales'
    targetRevision: dev
    path: overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
